version: '2'
services:
    mantozor-app:
        image: mantozor
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mantozor-mysql:3306/mantozor?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    mantozor-mysql:
        extends:
            file: mysql.yml
            service: mantozor-mysql
